version: "3"
services:
  app:
    build: ./backend
    depends_on:
      - db
    volumes:
      - ./backend:/go/src/app
    tty: true

  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    command: >
      --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --innodb_file_per_table --innodb_file_format=BARRACUDA --innodb_large_prefix=1
    ports:
      - 3307:3306
    volumes:
      - db_volume:/var/lib/mysql:cached
  migrate:
    build: ./db/migrations
    depends_on:
      - db
    command: [ "up" ]
    environment:
      WAIT_HOSTS: db:3306
      MIGRATIONS_DIR: /migrations
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db/migrations/migrations:/migrations
volumes:
  db_volume:
    driver: local
