version: "3"
services:
  app:
    build: ./backend/
    depends_on:
      - db
    volumes:
      - ./backend/:/go/src/app
    tty: true

  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    command: >
      --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --innodb_file_per_table --innodb_file_format=BARRACUDA --innodb_large_prefix=1
    ports:
      - 3307:3306
