import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import Header from "../components/Header"
import Footer from "../components/Footer"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <button className="bg-green-600 hover:bg-green-500 text-white rounded px-4 py-2">登録する</button>
      </main>
      <Footer />
    </div>
  )
}

export default Home
